minty_homepage_controller:
    path: /homepage/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"homepage", post_id:0, section:'homepage', topic_id:0, forum_id:0 }

minty_homepage_controller_podcasts:
    path: /podcasts/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"podcasts", post_id:0, section:'podcasts', topic_id:0, forum_id:0 }

minty_homepage_controller_tutorials:
    path: /tutorials/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"tutorials", post_id:0, section:'tutorials', topic_id:0, forum_id:0 }

minty_homepage_controller_diaries:
    path: /diaries/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"diaries", post_id:0, section:'diaries', topic_id:0, forum_id:0 }

minty_homepage_controller_reviews:
    path: /reviews/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"reviews", post_id:0, section:'reviews', topic_id:0, forum_id:0 }

minty_homepage_controller_links:
    path: /links/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"links", post_id:0, section:'links', topic_id:0, forum_id:0 }

minty_homepage_controller_comps:
    path: /comps/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"comps", post_id:0, section:'comps', topic_id:0, forum_id:0 }
