minty_homepage_controller:
    path: /homepage/{command}/{post_id}/{section}/{topic_id}/{forum_id}
    defaults: { _controller: minty.homepage.controller.main:handle, command:"select", post_id:0, section:'none', topic_id:0, forum_id:0 }
